=== eldiosx/animeweb/xml/animes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- Definir variables -->
  <xs:simpleType name="stringtype">
    <xs:restriction base="xs:string" />
  </xs:simpleType>

  <xs:simpleType name="inttype">
    <xs:restriction base="xs:positiveInteger" />
  </xs:simpleType>

  <xs:simpleType name="dectype">
    <xs:restriction base="xs:decimal" />
  </xs:simpleType>

  <xs:simpleType name="libraryidtype">
    <xs:restriction base="xs:string">
      <xs:pattern value="([a-zA-Z])*" />
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="librarytype">
    <xs:sequence>
      <xs:element name="name" type="stringtype" />
      <xs:element name="quantity" type="inttype" />
      <xs:element name="servercountry" type="stringtype" />
    </xs:sequence>
  </xs:complexType>
<!-- END Definir variables -->
  <xs:complexType name="animetype">
    <!-- <xs:complexContent>
      <xs:extension base="xs:string">
        <xs:attribute name="lang" type="xs:string" />
      </xs:extension>
    </xs:complexContent> -->
    <xs:sequence>
      <xs:element name="title" type="stringtype" />
      <xs:element name="director" type="stringtype" />
      <xs:element name="category" type="stringtype" maxOccurs="4" />
      <xs:element name="view" type="inttype" />
      <xs:element name="popularity" type="dectype" />
      <xs:element name="episodes" type="inttype" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="animestype">
    <xs:sequence>
      <xs:element name="language" type="stringtype" />
      <xs:element name="library" type="librarytype" />
      <xs:element name="anime" maxOccurs="unbounded" type="animetype" />
    </xs:sequence>
    <xs:attribute name="libraryid" type="libraryidtype" use="required" />
  </xs:complexType>

  <xs:element name="animes" type="animestype" />

</xs:schema>

=== eldiosx/animeweb/xml/animes.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="xml.css"
  title="DataBase" media="screen"
  type="text/css"?>
<animes libraryid="Default"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="animes.xsd">
    <language>Spanish</language>
    <library>
        <name>Animes</name>
        <quantity>12</quantity>
        <servercountry>Spain</servercountry>
    </library>
    <anime>
        <title>Attack On Titan</title>
        <director>Nose</director>
        <category>Gore</category>
        <category>Seinen</category>
        <view>1889889</view>
        <popularity>9</popularity>
        <episodes>500</episodes>
    </anime>
    <anime>
        <title>Death Note</title>
        <director>Nose</director>
        <category>Seinen</category>
        <category>Seinen</category>
        <view>45456</view>
        <popularity>9</popularity>
        <episodes>500</episodes>
    </anime>
    <anime>
        <title>Devilman Crybaby</title>
        <director>Nose</director>
        <category>Seinen</category>
        <category>Seinen</category>
        <view>5676767</view>
        <popularity>8</popularity>
        <episodes>500</episodes>
    </anime>
    <anime>
        <title>Ghost In the Shell</title>
        <director>Nose</director>
        <category>Seinen</category>
        <category>Seinen</category>
        <view>5667699</view>
        <popularity>521345</popularity>
        <episodes>500</episodes>
    </anime>
    <anime>
        <title>Inuyasha</title>
        <director>Nose</director>
        <category>Shonen</category>
        <category>Seinen</category>
        <view>8533323</view>
        <popularity>6</popularity>
        <episodes>167</episodes>
    </anime>
    <anime>
        <title>Kaguya Sama</title>
        <director>Nose</director>
        <category>Seinen</category>
        <category>Seinen</category>
        <view>2557</view>
        <popularity>5</popularity>
        <episodes>500</episodes>
    </anime>
    <anime>
        <title>Lain</title>
        <director>Nose</director>
        <category>Seinen</category>
        <category>Seinen</category>
        <view>46893</view>
        <popularity>7</popularity>
        <episodes>500</episodes>
    </anime>
    <anime>
        <title>Monster</title>
        <director>Nose</director>
        <category>Seinen</category>
        <category>Seinen</category>
        <view>889565</view>
        <popularity>8</popularity>
        <episodes>500</episodes>
    </anime>
    <anime>
        <title>One Punch Man</title>
        <director>Nose</director>
        <category>Seinen</category>
        <category>Seinen</category>
        <view>12667</view>
        <popularity>7</popularity>
        <episodes>500</episodes>
    </anime>
    <anime>
        <title>Parasyte</title>
        <director>Nose</director>
        <category>Seinen</category>
        <category>Seinen</category>
        <view>12667</view>
        <popularity>8</popularity>
        <episodes>500</episodes>
    </anime>
    <anime>
        <title>Psycho Pass</title>
        <director>Nose</director>
        <category>Seinen</category>
        <category>Seinen</category>
        <view>103467</view>
        <popularity>8</popularity>
        <episodes>500</episodes>
    </anime>
    <anime>
        <title>Tokyo Ghoul</title>
        <director>Nose</director>
        <category>Seinen</category>
        <category>Seinen</category>
        <view>129537</view>
        <popularity>9</popularity>
        <episodes>500</episodes>
    </anime>
</animes>
